/*
drop database if exists testewk; 
*/
create database testewk; 

use testewk;

create table cliente (
id int primary key auto_increment not null,
nome varchar(50) not null,
cidade varchar(40) not null,
uf varchar(2),
index(nome),
index(cidade),
index(uf)
) engine = innodb;

create table produto (
id int primary key auto_increment not null,
descricao varchar(50) not null,
precovenda double,
index(descricao)
) engine = innodb;

create table pedido (
id int primary key auto_increment not null,
dataemissao datetime,
id_cliente int,
valortotal double,
index(id_cliente, id),
constraint fk_cliente foreign key (id_cliente) references cliente(id)
) engine = innodb;

create table pedidoproduto (
id int primary key auto_increment not null,
id_pedido int,
id_produto int,
quantidade int,
valorunitario double,
valortotal double,
idalterado tinyint,
index(id_pedido, id),
constraint fk_pedido foreign key (id_pedido) references pedido(id),
constraint fk_produto foreign key (id_produto) references produto(id)
) engine = innodb;

create table pedidoprodutotmp (
id int primary key auto_increment not null,
id_pedidoproduto int,
id_produto int,
quantidade int,
valorunitario double,
valortotal double
) engine = innodb;

/* inseir dados para testes */
insert into cliente (nome, cidade, uf) values
("Cullen E. Slater","Pelotas","RS"),("Brody O. Rivera","Guarulhos","SP"),("Rahim R. Guthrie","Lauro de Freitas","BA"),
("Victoria O. Guy","Guarulhos","SP"),("Donna B. Welch","Cametá","PA"),("Jerome E. Johnston","Ribeirão Preto","SP"),
("Tanner A. Maxwell","Mogi das Cruzes","SP"),("Astra D. Patel","Mogi das Cruzes","SP"),("Hayfa T. Ford","Duque de Caxias","RJ"),
("Candace T. Booker","Uberlândia","MG"),("Priscilla I. Lyons","Jundiaí","SP"),("Orli D. Martin","Olinda","PE"),
("Carla I. Santana","Imperatriz","MA"),("Teegan Q. Tucker","Diadema","SP"),("Alan F. Haney","Novo Hamburgo","RS"),
("Sonia G. Saunders","Ribeirão Preto","SP"),("Nolan H. Sykes","Florianópolis","SC"),("Hollee A. Cook","Águas Lindas de Goiás","GO"),
("Ali G. Snyder","Ipatinga","MG"),("Jacqueline A. Frederick","Parauapebas","PA"),("Kevin X. Shepherd","Guarulhos","SP"),
("Jessamine Y. Walker","Londrina","PR"),("Carissa M. Lawrence","Valparaíso de Goiás","GO"),("Colorado R. Fitzgerald","Foz do Iguaçu","PR"),
("Macon T. Wright","Mogi das Cruzes","SP"),("Kyla H. Walton","Açailândia","MA"),("Clark T. Humphrey","Paulista","PE"),
("Nichole K. Barrett","Gravataí","RS"),("Jana F. Olsen","Piracicaba","SP"),("Jared D. Steele","Ilhéus","BA"),
("David A. Snyder","Carapicuíba","SP"),("Ferris A. Bates","Guarulhos","SP"),("Shelley F. Miranda","Duque de Caxias","RJ"),
("Emerson B. Ferguson","Crato","CE"),("Howard D. Stout","Juiz de Fora","MG"),("Teagan E. Joyner","Maranguape","CE"),
("Tara V. Bryant","Luziânia","GO"),("Lesley J. Copeland","Itabuna","BA"),("Marvin J. Copeland","Caruaru","PE"),
("Grace X. Ray","Osasco","SP"),("Lenore E. Chan","Belo Horizonte","MG"),("Chadwick M. Underwood","Salvador","BA"),
("Nichole D. Witt","Osasco","SP"),("Zane Z. Guthrie","Maringá","PR"),("Tana T. Lindsay","Divinópolis","MG"),
("Cade M. Vaughn","Ribeirão Preto","SP"),("Abdul I. Morrow","Governador Valadares","MG"),("Kasimir W. Foreman","Chapecó","SC"),
("Ursa J. Mcgee","Itabuna","BA"),("Ryan F. Mcconnell","Barra do Corda","MA"),("Noel N. Pena","Novo Hamburgo","RS"),
("Christine S. Hansen","Feira de Santana","BA"),("India X. Pruitt","Rio Grande","RS"),("Jessica Q. Atkinson","Piracicaba","SP"),
("Beck P. Velasquez","Duque de Caxias","RJ"),("August A. Willis","Osasco","SP"),("Uriel O. Yates","Porto Alegre","RS"),
("Quamar G. Kelley","Novo Hamburgo","RS"),("Aurora Z. Fischer","Mauá","SP"),("April U. Berry","Ribeirão das Neves","MG"),
("Jackson M. Kirby","Mogi das Cruzes","SP"),("Ramona B. Matthews","Uberlândia","MG"),("Aspen I. Mcclain","Caxias","MA"),
("Levi Y. Waller","Feira de Santana","BA"),("Fritz H. Moore","Camaçari","BA"),("Quin P. Moody","Feira de Santana","BA"),
("Mariko D. Levine","Rio Grande","RS"),("Kamal R. Morton","Piracicaba","SP"),("Tamara V. Newman","São José dos Pinhais","PR"),
("Upton Q. Barrera","Ribeirão das Neves","MG"),("Caryn Q. Cardenas","Patos","PB"),("Nora U. Norman","São João de Meriti","RJ"),
("Keefe F. Frost","Santa Rita","PB"),("Zia Z. Sharp","Jundiaí","SP"),("Brenna C. Cook","Mauá","SP"),
("Jenette S. Oliver","Petrolina","PE"),("Fleur X. Bradshaw","Patos","PB"),("Sandra O. Terrell","Ilhéus","BA"),("Quemby Y. Ball","Gravataí","RS"),("Jin C. Henry","Carapicuíba","SP"),
("Camilla T. Sawyer","Cajazeiras","PB"),("Lenore M. Wynn","Chapecó","SC"),("Mary D. Prince","Salvador","BA"),
("Jordan J. Villarreal","Guarulhos","SP"),("Gwendolyn R. Russell","Blumenau","SC"),("Delilah S. Maddox","Sousa","PB"),
("Victor U. Gillespie","Mauá","SP"),("Regan N. Wiggins","Mauá","SP"),("Walter M. Martin","Santa Luzia","MG"),
("Rebekah I. Mason","Juiz de Fora","MG"),("MacKensie Y. Garcia","Caruaru","PE"),("Denton E. Ramirez","Maracanaú","CE"),
("Simon Y. Harmon","Jundiaí","SP"),("Valentine E. Juarez","Campos dos Goytacazes","RJ"),("Axel W. Merrill","Sete Lagoas","MG"),
("Reagan K. Albert","Diadema","SP"),("Boris V. Manning","Belford Roxo","RJ"),("Nita W. Hatfield","Gravataí","RS"),
("Zorita Y. Joyner","Fortaleza","CE"),("Chantale W. Terrell","Jundiaí","SP");

insert into produto (descricao,precovenda) values
("Achocolatado Danone Danette 200ml",1.89),
("Achocolatado Ibituruna 1000ml",3.49),
("Achocolatado Magico 400g",2.59),
("Achocolatado Nescau Prontinho 1000ml",11.90),
("Aveia Quaker Flocos 200g",2.29),
("Aveia Quaker Flocos Finos 200g",3.99),
("Aveia Quaker Flocos Finos 500g",4.49),
("Aveia Quaker Oat Bran 250g",4.49),
("Bala de Janipapo Mana 20u",4.50),
("Barra Cereal Trio Mor/Cho Zero 20g",1.40),
("Barra Trio Cereal Cast/Choc Diet 25g",1.40),
("Bebida Lactea Nestle Suflair 270ml",3.99),
("Beiju Tradicional Canoão Un",7.79),
("Cafe 3 Coracões Cappuccino Choc. 180g",9.99),
("Cafe 3 Coracões Cappuccino Decaf/Fb 200g",4.99),
("Cafe 3 Coracões Ext Forte Alm. 250g",2.99),
("Cafe 3 Coracoes Trad. Almofada 250g",2.99),
("Cafe 3Coracoes Descaf. Vacuo 250g",6.99),
("Cafe Aliança Extra Forte 250g",1.49),
("Cafe Bahia Espresso 1000g",24.99),
("Cafe Brasileiro Pronto Cappuccino 200ml",1.79),
("Cappuccino 3 Coracoes Chocolate 20g",1.19),
("Cappuccino 3 Corações Classic 20g",1.19),
("Cappuccino 3 Corações Diet 140g",3.59),
("Cappuccino 3 Corações Extra Forte 180g",3.99),
("Cappuccino Jequie 200g",3.99),
("Cappuccino Shake 3 Corações 180g",9.59),
("Cereal Danone Milnutri Milho 230g",2.99),
("Cereal Nescau Nestle Choc.Rad 270g",11.99),
("Cereal Nestle Cob/Choc/Bra Galak Ball 30",1.50),
("Cereal Nestle Crunch 330g",12.99),
("Cereal Nestle Crunch 35g",1.89),
("Cereal Nestle Estrelitas 200g",4.69),
("Cereal Nestle Snow Flakes Choc. 320g",5.99),
("Cha Marata Boldo Do Chile 10g",3.99),
("Cha Matte Leao Diet 300ml",1.39),
("Leite Longa Vida Vale Dourado Int. 1L",3.29),
("Leite Nestle Molico Desnatado 280g",19.80),
("Leite Nestle Nan 1 450g",19.99),
("Leite Nestle Nan 2 450g",15.99),
("Leite Nestle Nan 2 Pro  400g",15.99),
("Leite Nestle Nestogeno 2º Sem 400g",11.99),
("Neston Nestle Vit. Maça/Ban/Mam 250ml",1.19),
("Sucrilhos Kelloggs Chocolate 25g",0.15),
("Sustagen Banana Calcio+Prot 400g",27.99),
("Sustagen Chocolate 400g",19.99),
("Sustagen Chocolate 500g",17.99),
("Sustagen Kids Chocolate 380g",14.98),
("Sustagen Kids Morango 380g",14.98),
("Sustagen Morango 400g",14.99),
("Sustagen Morango 500g",17.99),
("Toddy Quaker Choc. Original Sache 300g",3.49),
("Velas Prata Nº6 8X23g",6.99),
("Bandeja Laminada Plac Nº7 45x52",3.80),
("Copo Nobres Cristal Desc. 50x200ml",6.99),
("Copo Plast. Paramount 400ml",3.49),
("Copo Zanatta Cristal 100x200ml",2.99),
("Embalagem Alumínio Redonda M",0.10),
("Embalagem Freezer Fortlar 5kg",7.99),
("Embalagem P/ Quentinha Akuminic",0.26),
("Embalagem Queijinho Un",0.55),
("Etiqueta Filiz 61x40 TP80 Lisa Adv.",11.99),
("Fitilho Celofone Fino Cores Sort.50mt",2.00),
("Fitilho Celofone Largo Amarelo 50mt",5.40),
("Folha Aluminio Wyda 30cmx4mt",2.79),
("Forma Regina Papel Tam. Branca 4 100un",0.99),
("Forma Regina Papel Tam. Rosa 5 100un",0.49),
("Formas Pao Integral",3.00),
("Garrafa Plastica C/ Tampa 500ml",1.00),
("Guardanapo Malu 14x14cm 200Un",1.99),
("Guardanapo Malu 21x23cm 50Folhas",1.59),
("Guardanapo Perola 14x14 200un",0.79),
("Prato Regina Laminado Nº 07",1.80),
("Prato Regina Laminado Nº 5 28 cm",1.80),
("Saco de Lixo Grande 100L C/100un",0.21),
("Saco Farinha Vazio de 25",1.00),
("Saco Lixo Lukplast Preto 100Litros",0.99),
("Saco P. 20x15 H. Dog Elioplast",9.76),
("Saco P/ Lixo Clarus 100 Litros",2.99),
("Saco P/ Lixo Clarus 30 Litros",2.80),
("Saco P/ Lixo Clarus 50 Litros",2.89),
("Saco Plastico Liso 15x30 1Kg",0.63),
("Saco Plastico Liso Polipro 21x32",1.00),
("Tampa Copaza TP-08/P-15/C-550 50un",2.82),
("Tampa Copobras Cristal 50x200ml",4.30),
("Tampa Zanata Descart. TS-55ES 50x250ml",1.65),
("Toalha Papel Extrusa Interfolhas 1000un",11.99),
("Colonia Snoopy Aloe Vera Calendula 220ml",5.99),
("Desodorante Dove Aerosol Sensitive 100g",12.99),
("Desodorante Dove Aerosol Sensitive 103g",12.99),
("Desodorante Dove Aerosol Silk 100g",11.99),
("Desodorante Dove Aerosol Silk 103g",9.80),
("Desodorante Rastro Aerossol 90g",8.99),
("Desodorante Rastro Spray 90ml",2.99),
("Desodorante Rexena Aeresol Sensitive 105",13.99),
("Desodorante Rexona Roll On Active 50ml",6.99),
("Desodorante Rexona Roll On Cotton 50ml",5.99),
("Talco Johnson's Baby 200g",5.99),
("Talco York Baby Suave 200g",4.99),
("Agua Coco Ducoco 1000ml",8.99);
